addLayer("ach", {
    startData() { return {
        unlocked: true,
        points: new Decimal(0),
    }},
    symbol:"<h2 style='color:#824200'>❂</h2>",
    color:"#FFF176",
        nodeStyle: {"background": "radial-gradient(circle, #FFF176 15%, #FF8F00 90%)", 'border-radius': '45%', 'width': '80px', 'height': '80px'},
    row: "side",
    layerShown() {return true},

    resource: "achievements",
    baseResource: "points",
    baseAmount() {return player.points },
    type: "none",

   achievements: {
    11: {
        name:"first is alway free",
        done() {return hasUpgrade('p',11)},
        tooltip() {return "get the first power upgrade"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 16))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    12: {
        name:"double probably isn't slight",
        done() {return hasUpgrade('p',13)},
        tooltip() {return "get the third power upgrade"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 16))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    13: {
        name:"a very small amount of point",
        done() {return player.points.gte(100)},
        tooltip() {return "get 100 points"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 16))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    14: {
        name:"milestone time",
        done() {return hasMilestone('p',0)},
        tooltip() {return "get the first power milestone"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 16))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    15: {
        name:"that got expensive fast",
        done() {return hasUpgrade('p',22)},
        tooltip() {return "get the eigth power upgrade"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 16))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    16: {
        name:"even more milestones",
        done() {return hasMilestone('p', 4)},
        tooltip() {return "get the fifth power milestone"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 16))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    21: {
        name:"time for a new layer",
        done() {return player.r.points.gte(1)},
        tooltip() {return "get 1 progress"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 26))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    22: {
        name:"milestones galore",
        done() {return hasMilestone('r', 2)},
        tooltip() {return "get the third progress milestone"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 26))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    23: {
        name:"points without points?",
        done() {return (player.points.gte(15000) && !(hasUpgrade('p',11)))},
        tooltip() {return "get 15000 points with the first power upgrade"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 26))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    24: {
        name:"very very useful",
        done() {return (hasMilestone('r',5))},
        tooltip() {return "get the sixth progress milestone"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 26))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    25: {
        name:"time to automate",
        done() {return (hasMilestone('r',6))},
        tooltip() {return "get the seventh progress milestone"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 26))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    26: {
        name:"all the filler",
        done() {return (hasUpgrade('p',35))},
        tooltip() {return "get power upgrade 'probably not'"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 26))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    31: {
        name:"lets speed this up",
        done() {return (player.s.points.gte(1))},
        tooltip() {return "get 1 speed point"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 36))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    32: {
        name:"lets ACTUALLY speed this up",
        done() {return (getBuyableAmount('s',12)>0)},
        tooltip() {return "get 1 'more points for me' from the speed layer"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 36))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    33: {
        name:"now were really going",
        done() {return (getBuyableAmount('s',13)>0)},
        tooltip() {return "get 1 'can i get some power?' from the speed layer"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 36))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    34: {
        name:"yet another row 2 layer",
        done() {return (player.r.points.gte(20))},
        tooltip() {return "get 20 progress"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 36))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    35: {
        name:"finally some automation",
        done() {return (hasUpgrade('a',12))},
        tooltip() {return "get the second automation upgrade"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 36))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    36: {
        name:"speedy speed speeding up speed",
        done() {return (getBuyableAmount('s',14)>0)},
        tooltip() {return "get 1 'speedy speed' from the speed layer"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 36))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    41: {
        name:"no longer constantly speed reseting",
        done() {return (hasUpgrade('a',14))},
        tooltip() {return "get 1 'speedy speed' from the speed layer"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 46))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
    42: {
        name:"massive power gains",
        done() {return ((getBuyableAmount('s',11)>37)&& hasUpgrade('a',11))},
        tooltip() {return "get 1000% power per second (38 'faster generation' and auto upgrade 1)"},
        style(){return {"border-radius": "10% / 10%", "width": "100px", "height": "100px", 'background-color': (hasAchievement('ach',this.id)?(hasAchievement('ach', 46))?'#EAD176':'#FF8F60':'#bf8f8f' )}},
        onComplete() {player['ach'].points = player['ach'].points.add(1) },
    },
   },

    tabFormat: [
        ["display-text", function() {return "you have achieved <h2 style='color:#FFF176'>" + player.ach.achievements.length + " / 20</h2> achievements"}],
        "blank",
        "blank",
        ["row", [["achievement", 11], ["achievement", 12], ["achievement", 13], ["achievement", 14], ["achievement", 15], ["achievement", 16]]],
        ["row", [["achievement", 21], ["achievement", 22], ["achievement", 23], ["achievement", 24], ["achievement", 25], ["achievement", 26]]],
        ["row", [["achievement", 31], ["achievement", 32], ["achievement", 33], ["achievement", 34], ["achievement", 35], ["achievement", 36]]],
        ["row", [["achievement", 41], ["achievement", 42], ["achievement", 43], ["achievement", 44], ["achievement", 45], ["achievement", 46]]],
    ],
})